version: "3.8"

services:
  app:
    container_name: backend-prod
    image: artrip-backend:latest
    build:
        target: production
    ports:
      - 882:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      redis:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    restart: always
    volumes: !reset []
    env_file:
      - .env


  db: !reset {}
  redis: !reset {}

  elasticsearch:
    container_name: elasticsearch-prod
    environment: 
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true

    ports: !reset
      - "9202:9200"
      - "9302:9300"
    volumes:
      - elasticsearch-prod-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  elasticsearch-prod-data:
