version: "3.8"

services:
  app:
    container_name: backend-stage
    image: artrip-backend:latest
    build:
        target: production
    ports:
      - 881:8080
    environment:
      - SPRING_PROFILES_ACTIVE=stage
    depends_on:
      elasticsearch:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes: []
    env_file:
      - .env
  
  db: !reset {}
  redis: !reset {}

  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: elasticsearch-stage
    ports: 
      - 9201:9200
      - 9301:9300
    environment: 
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - elasticsearch-stage-data:/usr/share/elasticsearch/data

volumes:
  redis-stage-data:
  elasticsearch-stage-data: