version: "3.8"

services:
  java:
    container_name: backend-prod
    image: artrip-backend:latest
    build:
        target: production
    ports:
      - 882:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      redis:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    restart: always
    volumes: !reset []
    env_file:
      - .env


  db: !reset {}
  redis: !reset {}

  elasticsearch:
    build:
      context: ./docker/elasticsearch
    container_name: elasticsearch-stage
    ports:
      - "${ELASTICSEARCH_PORT:-9201}:9200"
      - "${ELASTICSEARCH_TRANSPORT_PORT:-9301}:9300"
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  elasticsearch-prod-data:
