spring:
  datasource:
    url: jdbc:mysql://localhost:33069/artrip?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: artrip1!

  data:
    redis:
      host: localhost
      port: 63799

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google

logging:
  level:
    root: INFO
    org.atdev.artrip: DEBUG
    org.springframework.boot.devtools: DEBUG